import type {
  User,
  Court,
  Coach,
  CourtBooking,
  CoachSession,
  ProgressReport,
} from "@/types";

export const mockUsers: User[] = [
  {
    id: "1",
    email: "student@example.com",
    fullName: "John Doe",
    role: "student",
    phone: "+1234567890",
    organizationId: "org1",
    branchId: "branch1",
    status: "active",
  },
  {
    id: "2",
    email: "coach@example.com",
    fullName: "Jane Smith",
    role: "coach",
    phone: "+1234567891",
    organizationId: "org1",
    branchId: "branch1",
    status: "active",
  },
  {
    id: "3",
    email: "admin@example.com",
    fullName: "Admin User",
    role: "admin",
    organizationId: "org1",
    status: "active",
  },
  {
    id: "5",
    email: "player@example.com",
    fullName: "Casual Player",
    role: "player",
    phone: "+1234567892",
    organizationId: "org1",
    branchId: "branch1",
    status: "active",
  },
];

export const mockCourts: Court[] = [
  {
    id: "1",
    name: "Court 1",
    type: "outdoor",
    pricePerHour: 50,
    description: "Premium outdoor court with excellent lighting",
    status: "active",
    branchId: "branch1",
  },
  {
    id: "2",
    name: "Court 2",
    type: "indoor",
    pricePerHour: 60,
    description: "Climate-controlled indoor court",
    status: "active",
    branchId: "branch1",
  },
  {
    id: "3",
    name: "Court 3",
    type: "outdoor",
    pricePerHour: 45,
    description: "Standard outdoor court",
    status: "active",
    branchId: "branch1",
  },
];

export const mockCoaches: Coach[] = [
  {
    id: "1",
    userId: "2",
    experienceYears: 10,
    bio: "Professional tennis coach with 10 years of experience",
    hourlyRate: 80,
    user: mockUsers[1],
  },
  {
    id: "2",
    userId: "4",
    experienceYears: 5,
    bio: "Experienced coach specializing in youth development",
    hourlyRate: 60,
    user: {
      id: "4",
      email: "coach2@example.com",
      fullName: "Mike Johnson",
      role: "coach",
      organizationId: "org1",
      branchId: "branch1",
    },
  },
];

export const mockBookings: CourtBooking[] = [
  {
    id: "1",
    organizationId: "org1",
    branchId: "branch1",
    userId: "1",
    courtId: "1",
    coachId: null,
    bookingType: "COURT_ONLY",
    bookingDate: "2024-03-15",
    startTime: "10:00",
    endTime: "11:00",
    durationMinutes: 60,
    totalPrice: 50,
    paymentStatus: "paid",
    bookingStatus: "confirmed",
    createdAt: "2024-03-10T10:00:00Z",
    updatedAt: "2024-03-10T10:00:00Z",
  },
  {
    id: "2",
    organizationId: "org1",
    branchId: "branch1",
    userId: "5",
    courtId: "2",
    coachId: "1",
    bookingType: "COURT_COACH",
    bookingDate: "2024-03-20",
    startTime: "14:00",
    endTime: "16:00",
    durationMinutes: 120,
    totalPrice: 280,
    paymentStatus: "paid",
    bookingStatus: "confirmed",
    createdAt: "2024-03-15T10:00:00Z",
    updatedAt: "2024-03-15T10:00:00Z",
  },
];

export const mockSessions: CoachSession[] = [
  {
    id: "1",
    organizationId: "org1",
    branchId: "branch1",
    coachId: "1",
    courtId: "1",
    sessionDate: "2024-03-15",
    startTime: "14:00",
    durationMinutes: 60,
    sessionType: "private",
    status: "scheduled",
    studentIds: ["1"],
    createdAt: "2024-03-10T10:00:00Z",
    updatedAt: "2024-03-10T10:00:00Z",
  },
  {
    id: "2",
    organizationId: "org1",
    branchId: "branch1",
    coachId: "1",
    courtId: null,
    sessionDate: "2024-03-20",
    startTime: "10:00",
    durationMinutes: 90,
    sessionType: "private",
    status: "scheduled",
    studentIds: ["1"],
    createdAt: "2024-03-15T10:00:00Z",
    updatedAt: "2024-03-15T10:00:00Z",
  },
];

export const mockReports: ProgressReport[] = [
  {
    id: "1",
    organizationId: "org1",
    branchId: "branch1",
    coachId: "1",
    studentId: "1",
    sessionId: "1",
    sessionDate: "2024-03-10",
    forehandScore: 7,
    backhandScore: 6,
    serveScore: 8,
    footworkScore: 7,
    staminaScore: 6,
    attendance: "present",
    overallComment: "Great improvement in serve technique",
    improvementPlan: "Focus on backhand consistency",
    nextGoal: "Improve backhand to level 7",
    createdAt: "2024-03-10T15:00:00Z",
    updatedAt: "2024-03-10T15:00:00Z",
  },
  {
    id: "2",
    organizationId: "org1",
    branchId: "branch1",
    coachId: "1",
    studentId: "1",
    sessionId: null,
    sessionDate: "2024-03-05",
    forehandScore: 6,
    backhandScore: 5,
    serveScore: 7,
    footworkScore: 6,
    staminaScore: 5,
    attendance: "present",
    overallComment: "Good progress overall",
    improvementPlan: "Work on stamina",
    nextGoal: "Increase stamina score",
    createdAt: "2024-03-05T15:00:00Z",
    updatedAt: "2024-03-05T15:00:00Z",
  },
];
